services:
  - type: web
    name: aurora-roasters
    env: node
    plan: free
    buildCommand: ""
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
